name: build

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: superbrobenji/async-queue/actions/workflows/pre-build.yml@main
  build:
    needs: version-bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun run build
