name: "Main - PR Label Checker"
on:
  pull_request:
    branches:
      - main
    types:
      - reopened
      - edited
      - labeled
      - unlabeled
jobs:
  check_labels:
    name: "Check PR Labels"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mheap/github-action-required-labels@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: "major, minor, patch"
