name: pre-build

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v4
      - name: setup bun
        uses: oven-sh/setup-bun@v2
      - name: install dependencies
        run: bun i
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: test code and get coverage
        run: bun run test
