name: release

on:
  release:
    types: [created]

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: install dependencies
        run: bun i
      - name: test code and get coverage
        run: bun run test
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun run build
      - name: "Check file existence"
        uses: andstor/file-existence-action@v3
        with:
          files: "dist/index.js, dist/cjs.js, dist/cjs.js.map, dist/index.d.ts, dist/index.d.ts.map, dist/index.js.map "
          fail: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
